### ISSUE TITLE
Contribution-Criteria is not competed

### ISSUE THREAD

**Issue by Mohitkumar6122** [moja-global/About_moja_global#111]
**What does the current documentation state?**

To Be Completed
**Where is this stated?**

About_moja_global/Governance/Contribution-Criteria.md

**Why do you want to improve the statement?**
Most of new contributors can get a lot of information from contribution criteria but this markdown file is not completed.

**Proposed statement**
I can rewrite and fill all the criteria which is neccesary for first time contribution. 

**Additional info**
could you look into  this issue  @Tlazypanda

**Comment by Patamap** [comment]
Thank you for the issue and offering help. That is great!!!.
And could this be part of https://github.com/moja-global/GSoD.moja_global_docs? @Tlazypanda

**Comment by Mohitkumar6122** [comment]
> Thank you for the issue and offering help. That is great!!!.
> And could this be part of https://github.com/moja-global/GSoD.moja_global_docs? @Tlazypanda

welcome :blush: can i contribute to it ?

**Comment by Patamap** [comment]
yes, definitely. You can assign yourself to this issue and start the pull request. 

If you have any questions, please let @gmajan @Tlazypanda  know.

**Comment by Mohitkumar6122** [comment]
@gmajan @Tlazypanda  could you tell me something about contibution criteria that is what are diffrent requirements to contribute to this organization.. ?
