### ISSUE TITLE
Update labels on moja global repositories 

### ISSUE THREAD

**Issue by shubhamkarande13** [moja-global/About_moja_global#114]
**Describe the bug**

The issue labels on the repos are inconsistent and this may cause problems later hence they need to be updated. 

**Proposed Solution**
Using [copy-github-labels-cli tool ](https://github.com/jvandemo/copy-github-labels-cli) we will standardise the labels across multiple repositories.

@gmajan @Tlazypanda @Patamap

**Comment by shubhamkarande13** [comment]
**Update:**

Under @Tlazypanda 's guidance, I have copied all the labels from About_moja_global repo to all the other repos under moja global organisation.

**To do:**

To discuss and take further steps to clean up redundant labels in each repository.

**Comment by Patamap** [comment]
@shubhamkarande13, please kindly refer to the label from this document link,  https://docs.google.com/document/d/1Yxyu9rfrRc94s3e3lhKFjmcOnudsqrs-fqxYsSJ9QAc/edit

**Comment by aornugent** [comment]
@sarthakkundra has recently updated the labels for GSoD'21
