### ISSUE TITLE
Update the Contribution Criteria

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/About_moja_global#120]
**What does the current documentation state?**

The Current Documentation states: `To Be Completed`.

**Where is this stated?**

This is stated here: https://github.com/moja-global/About_moja_global/blob/master/Governance/Contribution-Criteria.md

**Why do you want to improve the statement?**

As First Time Contributors roll over to Moja Global, they would look for specific resources to understand how they can contribute to Moja Global. The `About_moja_global` is a good place to start with, and I gave it a lot of readings. However, I found the Contribution Criteria yet to be completed. 

**Proposed statement**

This can be a good place to set some realistic expectation about what Contributors can do right here and what should be the best practices to be followed. Some of the specifics that can be added to this Documentation File can be seen [here](https://docs.moja.global/en/latest/contributing/index.html) but on further discussions, we can add in more details as well.

**Additional info**

I would like to work on the same ✌️ 

Since I am already on the Slack, I can contact the specific Stakeholders on what can be done about this and further improved.

cc: @gmajan @aornugent @Patamap

**Comment by aornugent** [comment]
Sounds great Harsh! @Tlazypanda - is anyone else working on this?

**Comment by raghavraj-27** [comment]
I am a beginner. I would like to work on this. Can you please assign it to me and guide me a little bit about what to write in it.

**Comment by aornugent** [comment]
Hey @HarshCasper - is this something that @raghavraj-27   can take up? I think your suggestion to copy the same information as RTD is a good idea.

**Comment by HarshCasper** [comment]
Sure @aornugent 

Assigning you the same @raghavraj-27 - Ping me on Slack if you need any help or drop a comment here :rocket:
