### ISSUE TITLE
Adding Developer Certificate of Origin (DCO) GitHub action

### ISSUE THREAD

**Issue by iamrajiv** [moja-global/About_moja_global#126]
**Is your feature request related to a problem? Please describe.**
In the pull request template, there is a checklist for the Developer Certificate of Origin (DCO) but there is no GitHub action to validate whether the person who has made the pull request had signed DCO or not.

**Describe the solution you'd like**
Adding Developer Certificate of Origin (DCO) GitHub action something like [Probot: DCO](https://github.com/probot/dco).

**Additional context**
Probot: DCO is a GitHub Integration built with [probot](https://github.com/probot/probot) that enforces the [Developer Certificate of Origin](https://developercertificate.org/) (DCO) on Pull Requests. It requires all commit messages to contain the `Signed-off-by` line with an email address that matches the commit author.

**Comment by iamrajiv** [comment]
@gmajan @Tlazypanda @aornugent I want to work on this.

**Comment by iamrajiv** [comment]
@gmajan @Tlazypanda @aornugent his GitHub action is also needed in other repositories like `FLINT`, `FLINT.Cloud` etc. I would like this implement this across relevant moja global projects.

**Comment by gmajan** [comment]
the Signed-off-by line 
is indeed required across all repos.
I think it is a good idea to suggest to @aornugent

**Comment by HarshCasper** [comment]
Done! It works across most of the repositories now :rocket:
