### ISSUE TITLE
Add DNS for join.moja.global

### ISSUE THREAD

**Issue by aornugent** [moja-global/About_moja_global#127]
I can never remember our Slack link and would like to set up a more memorable domain name. We'll also need to update our comms with the new address.

Here is the Slack invite: https://join.slack.com/t/mojaglobal/shared_invite/zt-o6ta1ug0-rVLjAo460~d7JbZ~HpFFtw

Many thanks!

**Comment by Tlazypanda** [comment]
Hey @aornugent I don't have access to do this the Linux Foundation team handles the website :sweat_smile:  this for reference https://github.com/moja-global/moja_global_docs/issues/14

**Comment by aornugent** [comment]
Ah that's right! Thanks Sneha
