### ISSUE TITLE
Rename `About.moja.global`

### ISSUE THREAD

**Issue by aornugent** [moja-global/About_moja_global#136]
I'd like to standardise our naming conventions to follow those laid down by the maintainers. However this repo is a trickier than most as it is reference in other places. We'll need to double check any backlinks and standardise them as we make this change.

**Comment by Ayush7614** [comment]
@aornugent i would like to work on the issue please assign me

**Comment by aornugent** [comment]
Thanks @Ayush7614 - moving this convo to #138
