### ISSUE TITLE
Update branding guidelines

### ISSUE THREAD

**Issue by aornugent** [moja-global/About_moja_global#137]
@ksocksTR33Z has an awesome new set of brand assets, but these are not reflected in our governance docs: https://github.com/moja-global/About_moja_global/blob/master/Governance/BRANDING.md

**Comment by ksocksTR33Z** [comment]
Hi All, we have all of the assets here for everyone to use. I'm not sure how to update the governance docs myself so if you could help support @sarthakkundra that would be fantastic: https://drive.google.com/drive/folders/156SUapBc0XdLkkcgL6WZUPtsBCXDQiTI?usp=sharing
