### ISSUE TITLE
Grouping small repos in science section

### ISSUE THREAD

**Issue by arushi-mittal** [moja-global/About_moja_global#156]
**What does the current documentation state?**
Currently, there are many small repositories (1-2 documents) that can be grouped together in a science section to reduce the repository count.

**Where is this stated?**
Older repositories such as [FLINT.Module.Forest_biomass_model](https://github.com/moja-global/FLINT.Module.Forest_biomass_model), and [FLINT.Projections](https://github.com/moja-global/FLINT.Projections).

**Why do you want to improve the statement?**
To reduce the repository count and centralize everything in the science directory in the About_moja_global repo. This would allow people to see everything in one place and reduce reused docs in multiple places.

**Proposed statement**
Removing the existing smaller repos with very few documents and centralizing them in the Science directory in the About_moja_global repo.

**Additional info**
Add any useful information here.

**Comment by HarshCasper** [comment]
> Are we keeping it open for new contributors or can I take it up?

Let's keep it open for new contributors.

**Comment by Sukriti-sood** [comment]
I would like to work on this.

**Comment by SanjaySinghRajpoot** [comment]
Let me know if you need any help in this @Sukriti-sood 

Thank You
