### ISSUE TITLE
Add 'DevOps' working group info.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/About_moja_global#162]
**To Do:**

**Add a directory named as 'DevOps' in ['working-group'](https://github.com/moja-global/About_moja_global/tree/master/working-groups)**

Add the following sections:
- **About:** 
The 'About' part should be able to be a good introduction to the working group.

 Template:
- Status i.e Incubating
- About the DevOps working group.
- Meeting Details.
- Goal of the working group.
- Tools and Technologies.
- How can one get involved.

Have a look [here](https://github.com/moja-global/About_moja_global/blob/master/working-groups/user-interface/About.md) for reference.

- **MeetingNotes folder.** - This folder shall contain the meeting notes of the meetings (Here onwards.)

- **Agenda file.** - Should talk about the agenda for the upcoming meetings.

Get in touch with @HarshCasper over Slack for a review of the document and for information about this working group.
Refer to https://github.com/moja-global/About_moja_global/tree/master/working-groups/user-interface

**Comment by iharshit009** [comment]
Can I work on it @chicken-biryani ?

**Comment by chicken-biryani** [comment]
Hi, @iharshit009 how is the doc coming up?

**Comment by iharshit009** [comment]
Hey @chicken-biryani  Working on it will try to raise PR by this Saturday

**Comment by chicken-biryani** [comment]
@iharshit009 I'd recommend conversing with @HarshCasper over slack.

It may be possible that what and how you're going about building the document is not what's required by the lead.

To work in a more efficient manner please have a word with the lead, in this case @HarshCasper.

Thanks! :)
