### ISSUE TITLE
Add 'Documentation' working group info.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/About_moja_global#163]
**To Do:**

**Add a directory named as 'documentation' in ['working-group'](https://github.com/moja-global/About_moja_global/tree/master/working-groups)**

Add the following sections:
- **About:** 
The 'About' part should be able to be a good introduction to the working group.

 Template:
- Status i.e Active
- About the Documentation working group.
- Meeting Details.
- Goal of the working group.
- Tools and Technologies.
- How can one get involved.

Have a look [here](https://github.com/moja-global/About_moja_global/blob/master/working-groups/user-interface/About.md) for reference.

- **MeetingNotes folder.** - This folder shall contain the meeting notes of the meetings (Here onwards.)

- **Agenda file.** - Should talk about the agenda for the upcoming meetings.

Get in touch with @HarshCasper  for a review of the document and for information about this working group.
Refer to- https://github.com/moja-global/About_moja_global/tree/master/working-groups/user-interface

**Comment by Sukriti-sood** [comment]
@chicken-biryani Pleaae assign me..

**Comment by Shorla** [comment]
@chicken-biryani can I work on this? Though I noticed it has been assigned to @Sukriti-sood. Is it currently being worked on? or is there something else I can contribute to?

**Comment by chicken-biryani** [comment]
Hey, @Shorla that's up to @Sukriti-sood to decide.

All you'll have to do is copy-paste the content from the community website/working groups /  Documentation as the content is already up there.

Make the file structure similar to that of the user-interface folder.

**Comment by Shorla** [comment]
@Sukriti-sood if you think I should, I will like to get started right away.

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood if you think I should, I will like to get started right away.

Sorry for late reply.. but you can work on this.

**Comment by Shorla** [comment]
How do I get information on the documentation working group

**Comment by chicken-biryani** [comment]
@Shorla you'll find it on the community website. Under working groups... In the footer.
