### ISSUE TITLE
Add 'Modules' working group info.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/About_moja_global#164]
**To Do:**

**Add a directory named as 'Modules' in ['working-group'](https://github.com/moja-global/About_moja_global/tree/master/working-groups)**

Add the following sections:
- **About:** 
The 'About' part should be able to be a good introduction to the working group.

 Template:
- Status i.e Incubating
- About the Modules working group.
- Meeting Details.
- Goal of the working group.
- Tools and Technologies.
- How can one get involved.

Have a look [here](https://github.com/moja-global/About_moja_global/blob/master/working-groups/user-interface/About.md) for reference.

- **MeetingNotes folder.** - This folder shall contain the meeting notes of the meetings (Here onwards.)

- **Agenda file.** - Should talk about the agenda for the upcoming meetings.

Get in touch with @aornugent, @HarshCasper, &/or @chicken-biryani over Slack for a review of the document and for information about this working group.
Refer to https://github.com/moja-global/About_moja_global/tree/master/working-groups/user-interface **and** https://docs.google.com/document/d/1_7LffEtgvZKK5rj1ucfxzU1sX2ma8qVlW9AH_I3X1io/edit#heading=h.nnw3c4a4adpp

**Comment by tejaswari7** [comment]
@chicken-biryani I would like to take up this issue
Please assign this to me.

**Comment by chicken-biryani** [comment]
Hey, @tejaswari7 sure.

Please feel free to attend the documentation working group meetings to get guided on how to go about it. And do keep a touch with us on Slack #documentation.

This document will recuire a little brainstorming... As it's details aren't readily available.

Don't worry about the 'meeting details' part.

**Comment by tejaswari7** [comment]
> Hey, @tejaswari7 sure.
> 
> Please feel free to attend the documentation working group meetings to get guided on how to go about it. And do keep a touch with us on Slack #documentation.
> 
> This document will recuire a little brainstorming... As it's details aren't readily available.
> 
> Don't worry about the 'meeting details' part.

Sure!!
