### ISSUE TITLE
Add 'Mentorship' working group.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/About_moja_global#165]
**To Do:**

**Add a directory named as 'Mentorship' in ['working-group'](https://github.com/moja-global/About_moja_global/tree/master/working-groups)**

Add the following sections:
- **About:** 
The 'About' part should be able to be a good introduction to the working group.

 Template:
- Status i.e Incubating
- About the Mentorship working group.
- Meeting Details.
- Goal of the working group.
- Tools and Technologies.
- How can one get involved.

Have a look [here](https://github.com/moja-global/About_moja_global/blob/master/working-groups/user-interface/About.md) for reference.

- **MeetingNotes folder.** - This folder shall contain the meeting notes of the meetings (Here onwards.)

- **Agenda file.** - Should talk about the agenda for the upcoming meetings.

Get in touch with @aornugent, @HarshCasper, &/or @chicken-biryani over Slack for a review of the document and for information about this working group.

Refer to https://github.com/moja-global/About_moja_global/tree/master/working-groups/user-interface **and** https://docs.google.com/document/d/1_7LffEtgvZKK5rj1ucfxzU1sX2ma8qVlW9AH_I3X1io/edit#heading=h.nnw3c4a4adpp

**Comment by AmitKarnam** [comment]
I would like to take this up @chicken-biryani .

**Comment by HarshCasper** [comment]
@aornugent Would you like to lead this working group, if you have the bandwidth?

**Comment by aornugent** [comment]
Thanks @HarshCasper - happy to lead. Thanks @AmitKarnam for picking this up. Please tag me when you have a PR up and I can review and edit.

**Comment by AmitKarnam** [comment]
I had a go at this and with the help of @chicken-biryani , I have come up with a draft in the following Google form, please do review and suggest changes if any! Thank you!

Link : https://docs.google.com/document/d/18j9hYbXgd6x6_-6OeJV4MWdtlx-bsVbFd-GbcAmjFrk/edit#
