### ISSUE TITLE
Add 'Optimisation' working group info.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/About_moja_global#166]
**To Do:**

**Add a directory named as 'Optimisation' in ['working-group'](https://github.com/moja-global/About_moja_global/tree/master/working-groups)**

Add the following sections:
- **About:** 
The 'About' part should be able to be a good introduction to the working group.

 Template:
- Status i.e Incubating
- About the Optimisation working group.
- Meeting Details.
- Goal of the working group.
- Tools and Technologies.
- How can one get involved.

Have a look [here](https://github.com/moja-global/About_moja_global/blob/master/working-groups/user-interface/About.md) for reference.

- **MeetingNotes folder.** - This folder shall contain the meeting notes of the meetings (Here onwards.)

- **Agenda file.** - Should talk about the agenda for the upcoming meetings.

Get in touch with @aornugent, @HarshCasper, &/or @chicken-biryani over Slack for a review of the document and for information about this working group.
Refer to https://github.com/moja-global/About_moja_global/tree/master/working-groups/user-interface **and** https://docs.google.com/document/d/1_7LffEtgvZKK5rj1ucfxzU1sX2ma8qVlW9AH_I3X1io/edit#heading=h.nnw3c4a4adpp

**Comment by AayushSaini101** [comment]
Please assign this @chicken-biryani

**Comment by HarshCasper** [comment]
@chicken-biryani @AayushSaini101 A note: We don't know the scope of the Optimization working group **as of now**. It would be ideal to touch base with @aornugent to brainstorm what plans he has about getting started with this and who would ideally lead this.

**Comment by chicken-biryani** [comment]
@HarshCasper the lead- yes. I was thinking about adding the information for now and put it in 'incubating'.
