### ISSUE TITLE
Suggestions for improving the Contribution Guidelines

### ISSUE THREAD

**Issue by abhineet97** [moja-global/About_moja_global#38]
Hi!

I think that the current [contribution guidelines] can be vastly simplified.

Many of the guides like [`How-to-Report-Bugs.md`](https://github.com/moja-global/About-moja-global/blob/master/Contributing/How-to-Contribute-Code.md), [`How-to-Provide-User-Feedback.md`](https://github.com/moja-global/.github/blob/master/Contributing/How-to-Provide-User-Feedback.md), [`How-to-Request-a-New-Feature.md`](https://github.com/moja-global/.github/blob/master/Contributing/How-to-Request-a-New-Feature.md) can all be reduced into a single line:

> To report bugs, provide feedback, request new features, etc., please create a new issue by choosing an appropriate template from [here](https://github.com/moja-global/About_moja_global/issues/new/choose). 

We can also merge the more important guides like [`How-to-Contribute-Code.md`](https://github.com/moja-global/About-moja-global/blob/master/Contributing/How-to-Contribute-Code.md) and [`How-to-Contribute-Review-Science-Design.md`](https://github.com/moja-global/About-moja-global/blob/master/Contributing/How-to-Contribute-Review-Science-Design.md) into `CONTRIBUTING.md`. This will make the guidelines much easier to read.

Simple and easy to understand contribution guidelines can not only promote contributions but can also help us "create inclusive communities" (as reported by [GitHub's 2017 Open Source Survey]).

Please, let me know what you think. I'd be delighted to submit a PR implementing these suggestions :slightly_smiling_face: 

[contribution guidelines]: https://github.com/moja-global/About_moja_global/blob/master/CONTRIBUTING.md
[GitHub's 2017 Open Source Survey]: https://opensourcesurvey.org/2017/

**Comment by gmajan** [comment]
Hi Abhineet,
Thank you for the great suggestions. I am happy if you go ahead with this. 
Looking forward to your changes.
