### ISSUE TITLE
Adopt code of conduct for moja global projects 

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#42]
Issues: 
A clear and concise description of what the problem is. Ex. When I reach this point, I cannot [...]
Adopt a code of conduct (Contributor Covenant, https://www.contributor-covenant.org?) to set clear expectations for acceptable and unacceptable behavior in Moja global projects

Solution: 
Agree or write a code of conduct to set clear expectations and guidelines for contributor behavior in Moja global projects, have a general idea of how to handle violation reports should they ever happen.

Background:
Having a code of conduct for an open-source project is important. A company or organization has a human resources department and expectations for how employees are to behave, but an open-source project does not. Setting clear expectations for what behavior is appropriate or not is important, and also assures confidence in contributors that their experience will be positive.

See GitHub's open-source guide for a more in-depth explanation of the value of a code of conduct.

**Comment by gmajan** [comment]
Dear Patama,
We are using this code of conduct: https://github.com/moja-global/About_moja_global/blob/master/CODE_OF_CONDUCT.md

It is an open source initiative that is developing the code of conduct jointly so we learn from eachother. https://www.contributor-covenant.org/

I am however a bit worried that you did not see the code of conduct in the about-moja-global repo

**Comment by Patamap** [comment]
thanks for sharing!!! It would be good to have all info in one area. So it is easy to find for newcomer.

**Comment by gmajan** [comment]
I agree. What do you suggest? thx

**Comment by Patamap** [comment]
@gmajan, we can put to this code conduct to welcome bot msg which is coded and tested by @Tlazypanda and also add to Contributing Guideline document which is the part of @Sneha GSOD.

**Comment by gmajan** [comment]
But I think it already is in there? Maybe I do not really understand.

**Comment by Patamap** [comment]
@Tlazypanda can you please comment?

**Comment by Tlazypanda** [comment]
The code of conduct link is there in the welcome bot message
