### ISSUE TITLE
EPIC for Add Zulipbot to manage and optimize Github Workflow

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/About_moja_global#45]
**Is your feature request related to a problem? Please describe.**
@zulipbot is a GitHub workflow bot application for the Zulip organization and its repositories. Written in Node.js, the bot manages issues and pull requests in the repository in order to create a better workflow for Zulip contributors.

zulipbot's purpose is to work around various limitations in GitHub’s binary permissions and notifications systems to create a better workflow for our contributors. It allows anyone to perform issue triage (self-assigning and labeling issues), not just the core contributors trusted with full write access to the repository (which is the only model GitHub supports). Additionally, zulipbot monitors the activity of issues and pull requests, notifying contributors about new merge conflicts, continuous integration build results, inactivity, and more.

**Describe the solution you'd like**
We can install Zulipbot to our organization repositories by following this  installation guide [here](https://github.com/zulip/zulipbot/wiki/Installation). This will allow issues to get assigned to whoever comments first and also unassigned if there is inactivity for a given period of time reducing the work for maintainers.

See the instruction here: https://docs.google.com/document/d/1B1k2kRpAdtl9U8v-ze-uO56m8rldIuiAG1nQoZRpyDI/edit

**Additional context**
Screenshots showing the bot in action: - 
![image](https://user-images.githubusercontent.com/33183263/84342229-b2cce900-abc2-11ea-933e-77202e1b01ef.png)  

![image](https://user-images.githubusercontent.com/33183263/84342278-caa46d00-abc2-11ea-864e-6fd015f00c55.png)

**Comment by gmajan** [comment]
I like the idea. I am not totally clear yet how it will work but I will learn when we test it on the about-moja-global repository. After that we can roll it out to the other repos. Good idea. Thank you. Keep those ideas coming!!

**Comment by Patamap** [comment]
@Tlazypanda Thanks for the idea. It is great. Can we also create the add Project-bot to manage and optimize the Kanban board? Is that the Project- Bot best practice for board?

**Comment by Patamap** [comment]
The requirements in the issue itself are
1. The issue creator can assign the issue to him/herself with type "@name claim" 
2. The issue creator can unassign  the issue from him/herself with type "@name abandon"
3. The new creator can only chose the issue with label  with type "@name newcomer"
4.

**Comment by Tlazypanda** [comment]
@Patamap @gmajan So the zulipbot setup has been done and this can be closed. Moving to #63 to discuss more on contribution guidelines specific for zulipbot to be added to the readme so that contributors know what commands to write to claim issues and/or add labels. Thanks :v:
