### ISSUE TITLE
Add Welcome Bot to create an inclusive environment for new contributors

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/About_moja_global#46]
**Is your feature request related to a problem? Please describe.**
Welcome is a simple way to welcome new users based off maintainer defined comments.

The 3 plugins it combines with are new-issue-welcome(Comment to be posted to on first time issues) , new-pr-welcome(Comment to be posted to on PRs from first time contributors in your repository) and first-pr-merge(Comment to be posted to on pull requests merged by a first time user).

**Describe the solution you'd like**
We can setup [Welcome](https://probot.github.io/apps/welcome/) bot by adding the GitHub App to our organization repositories and configuring `.github/config.yml ` according to the content of the messages we want.

This will make the new contributors feel welcomed and at ease in interacting with the community.

**Additional context**
Screenshots that depict the Welcome bot in action:  

![image](https://user-images.githubusercontent.com/33183263/84342753-faa04000-abc3-11ea-83d8-f9515d07909f.png)

**Comment by gmajan** [comment]
Full support for this idea. Great that you have added it as an On-boarding milestone. Thx!
