### ISSUE TITLE
Add the reviewer to the issue page 

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#51]
Able to select the reviewers directly on the issue page.  It means 1, 2, 3  can review issues/new ideas to agree and approve together.

**Comment by Patamap** [comment]
@Tlazypanda @gmajan It looks like the reviewer is shown in the PR but not in the issue as the common behavior for github. So I close this issue as it is not needed.

**Comment by Tlazypanda** [comment]
@Patamap no no it's just for testing the project- board 😅

**Comment by Tlazypanda** [comment]
@Patamap yeah!

**Comment by Patamap** [comment]
@Tlazypanda Thanks!!! Closed the issue.
