### ISSUE TITLE
EPIC for Testing Tools (coverage/CI/CD/health check)

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#60]
The purpose of CI is here, https://github.com/moja-global/About_moja_global/issues/72 

Actions are 
1. Set up CI communication in SLACK. Done. 
https://app.slack.com/client/T1G1M5HPF/C015F595D0W/thread/D014MSKDFGW-1592806920.001400

2. Testing the FLINT (ask the question/engage Jim and Max) to get the gap and able to write the specification. 
https://github.com/moja-global/testarea/issues

3.  Set up server.  
@leitchy @mfellows @malfrancis 

4.  Set up CI code/tool

7.  Updated document: Use continuous integration (CI).

@Tlazypanda item 2 - item 6 will need the new issues for each item.

**Comment by gmajan** [comment]
As discussed in various places, the quality of the code should be combined with the IT and the science aspects of FLINT. There is a need to break down the science aspects into tests that can be run at pull request stage, at unit test stage and at deployment stage. How this can be done will require a discussion with the scientist in our team.
