### ISSUE TITLE
How to Deploy the application

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#61]
Need the simple instruction for those topics due to missing. 
1. Create a feature branch for development.

2. Create a tag ( semantic versioning rules).

3. Deploying the application.

**Comment by gmajan** [comment]
Would it pls be possible to elaborate a little bit so it is easier to understand? thx

**Comment by gmajan** [comment]
This discussion will be taken forward under CI discussion combined with QA/QC #60
