### ISSUE TITLE
Cleanup/Maintanent SLACK

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#65]
Cleanup/Maintanent SLACK in order to easy and transparent for everyone to use it. 

Need spec.

Part of EPIC https://github.com/moja-global/About_moja_global/issues/43

**Comment by Tlazypanda** [comment]
@Patamap @gmajan Updating here - greetbot setup on slack for 
- direct message when a newcomer joins 
- channel message for when newcomers join #gsoc-general

To be updated/changed acc to convenience of other slack members.
Can take this up in the next meeting 

Thanks all!! 🙌

**Comment by Patamap** [comment]
@Tlazypanda Thanks for elaborated. The greetbot moves to https://github.com/moja-global/About_moja_global/issues/71. So this issue keeps for cleanup/Maintanent SLACK.

**Comment by gmajan** [comment]
I have removed all channels that are no longer active. The next step will be to make SLACK public. This needs to be discussed in the TSC
