### ISSUE TITLE
EPIC for The community website

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#67]
The community website will have the following features:-

1. Information about our Workflow: The workflow will consist of the series of actions a new contributor can begin with i.e - claiming a first-timers issue, followed by creating a first-timers issue for someone else and helping others by providing feedback and reviewing their pull requests.
2. List of First-timer only issues: The list of issues specifically meant for first-timers or new contributors.
3. List of Stale issues: The list of issues that haven’t been worked on for a long period of time and hence are available to be picked by contributors.
4. List of Contributors: The list of contributors who have so far contributed to Moja Global repositories.
5. Recent Contributors: The list of contributors who have recently contributed to Moja Global repositories.
6. Links to join chat forums: Information and links to join the Slack com2munity to resolve their queries and have further discussions on the projects.

Refer to https://docs.google.com/document/d/1MoSOYdlUFV2ar9e_rG4P43ucwoMUO2mTQ9pjetRGdaY/edit# from @Tlazypanda:  Location of the community website.  See the example here; https://code.publiclab.org/

**Comment by gmajan** [comment]
Sneha will develop a detailed proposal how the community website can be widened after she has completed her work on onboarding. We will decide then how to get sufficient support on this item.
