### ISSUE TITLE
Set up automatic CI testing for new pull requests

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#72]
**Goal**: Set up [continuous integration](https://github.com/marketplace/category/continuous-integration) (CI) to build new pull requests against FLINT projects.

**Why CI?** 
CI is important for a project because it prevents simple mistakes or oversights making it into a production codebase. Effective test cases can be written to hook into any of the CI platforms available, such as TravisCI, CircleCI, and others.

CI is helpful for advanced contributors (especially in a small project) because of limited development time and the ease of making mistakes. It happens. It's a safeguard to help prevent mistakes from entering "production" code.

CI is helpful for new contributors because it provides instant feedback if a pull request breaks the project or not. A contributor can see feedback and a stacktrace of what went wrong so they can fix their issue or ask for specific help if needed (instead of waiting for a maintainer to review the PR and give that feedback).

**Details**
There are general test cases available for many programming languages. Those could be set up easily. More advanced CI would encourage contributors to write test cases into the code, and then CI platforms could execute those test cases.

Each FLINT project will likely need its own unique CI configuration, If developer bandwidth is low, some projects that are more "publicly visible" should be prioritized for CI coverage.

**Expected Outcome**
Pull requests to a FLINT project are tested and verified to build successfully before a maintainer reviews a new contribution; this helps prevent bad code making it into the code base and provides immediate feedback to new contributors to fix oversights or mistakes.

**Comment by Patamap** [comment]
@HarrisLawYFl

**Comment by gmajan** [comment]
This issue is discussed under EPIC #60
