### ISSUE TITLE
Add cppcheck and clang-tidy codequality checks as part of CI/CD 

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/About_moja_global#76]
**Describe the solution you'd like**
Currently the pull request is not tested on whether it is following cpp style conventions and other code quality checks. Static analysis tools such as cppcheck and clang-tidy can help us check pull requests and have better code maintainability in the future.

**Describe alternatives you've considered**
As per discussion with @kaskou we need to develop our own testing github actions to allow customization ahead. - https://github.com/Tlazypanda/cpp-clang-check is currently in preliminary stages and has been pre-released as a github actions on github marketplace.

We need to study the following existing tools to ensure this action has all these features - 
https://github.com/smay1613/cpp-linter-action
https://github.com/deep5050/cppcheck-action

**Comment by Tlazypanda** [comment]
Just noting @kaskou @gmajan @Patamap Currently the preliminary action tool can be seen in action here - https://github.com/Tlazypanda/FLINT/pull/1 :sweat_smile: Needs to developed further to only flag specific errors as per our codebase

**Comment by Tlazypanda** [comment]
Update here: @kaskou approved initial action tool, now moving to the next stage of modifying to add flags in the action (for example allowing users to edit the action script to check for specific flags for cppcheck such as only performance or as desired)
cc @gmajan @Patamap :v:

**Comment by gmajan** [comment]
@malfrancis @leitchy @mfellows is this in line with your discussion on Wednesday and can @Tlazypanda proceed? thx
