### ISSUE TITLE
Summary of Internal communication 

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#77]
Clear Communication though members play a big role to help everyone to work effectively together.  Summarize all internal communication and investigate if there is needed any update. 

How to do it
1.    Identify what are we doing for internal communication and the effectiveness2 of the current one. 
2.   The proposal the update the internal information. 
3.   Evaluate.
4.   Implemented

Why do it
When people come wanting to contribute, we need to help guide their first steps. Simple and easy access information and let them explore the "newcomer issues"  tasks are great ways to introduce how we work in mojo global by giving them a simple guideline and manageable area to focus on or work.  These internal communications get both newcomers and existed teams more comfortable with the project and could edge someone towards contributing bigger things. 

@gmajan @Tlazypanda

**Comment by gmajan** [comment]
@mojaglobalbot claim

**Comment by gmajan** [comment]
@mojaglobalbot unclaim

**Comment by gmajan** [comment]
What we need is a clear "architecture" of how the different community platforms fit together: Slack, github, community website, readthedocs, and regular website fit together with their own purpose but it might not be clear which platform is used for what communication.
This might have to be explained on the community website when we have completed it.
