### ISSUE TITLE
Add all contributor

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#81]
@all-contributors please add @juliancabezas for code.

**Comment by Patamap** [comment]
@all-contributors please add @saloni-garg  for code

**Comment by Patamap** [comment]
@all-contributors please add @yjko2 for code

**Comment by Patamap** [comment]
@all-contributors please add @sulays  for code

**Comment by Patamap** [comment]
@all-contributors please add @parth-gr  for code

**Comment by Patamap** [comment]
@all-contributors please add @abhi211199  for code

**Comment by gmajan** [comment]
@all-contributors please add @Tonnix  for code.

**Comment by Patamap** [comment]
@all-contributors please add @juliancabezas  for code

**Comment by Patamap** [comment]
@all-contributors please add @abhineet97  for code

**Comment by Patamap** [comment]
@all-contributors please add @abhineet97 for code

**Comment by Patamap** [comment]
@all-contributors please add @abhi211199  for code

**Comment by Patamap** [comment]
@all-contributors please add @slkull for code

**Comment by Patamap** [comment]
@all-contributors please add @vatsalyatandon for code

**Comment by Patamap** [comment]
@all-contributors please add @parth-gr for code

**Comment by Patamap** [comment]
@all-contributors please add @abhi211199  for code

**Comment by Patamap** [comment]
@all-contributors please add @abhineet97  for code

**Comment by Patamap** [comment]
@all-contributors please add @sulays for code

**Comment by Patamap** [comment]
@all-contributors please add @Tlazypanda  for code

**Comment by Patamap** [comment]
@all-contributors please add @tgoswamy for code

**Comment by Patamap** [comment]
@all-contributors please add @trydave for code

**Comment by Patamap** [comment]
@all-contributors please add @jahnvigupta for code

**Comment by Patamap** [comment]
@all-contributors please add @7ayushgupta for code

**Comment by Patamap** [comment]
@all-contributors please add @Tonnix for code

**Comment by Patamap** [comment]
@all-contributors please add @Ixw123for code

**Comment by Patamap** [comment]
@all-contributors please add https://github.com/Ixw123 for code

**Comment by Patamap** [comment]
@all-contributors please add @Ixw123 for code

**Comment by Patamap** [comment]
@all-contributors please add @shubhamkarande13 for code

**Comment by Patamap** [comment]
@all-contributors please add @saloni-garg for code

**Comment by Patamap** [comment]
@all-contributors please add @yjko2 for code

**Comment by Mohitkumar6122** [comment]
@all-contributors please add @Mohitkumar6122 for code for code

**Comment by shubhamkarande13** [comment]
@aornugent Shouldn't we update the contributors? It has almost been a year!  😅

**Comment by aornugent** [comment]
That'd be fantastic, thanks @shubhamkarande13!

**Comment by HarshCasper** [comment]
@all-contributors bot please add @HarshCasper for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @HarshCasper for documentation

**Comment by HarshCasper** [comment]
@all-contributors bot please add @sarthakkundra for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @sarthakkundra for documentation

**Comment by HarshCasper** [comment]
@all-contributors bot please add @chicken-biryani for documentation

**Comment by HarshCasper** [comment]
@all-contributors bot please add @iamrajiv for documentation

**Comment by HarshCasper** [comment]
@all-contributors bot please add @iamrajiv for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @waridrox for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @waridrox for design

**Comment by HarshCasper** [comment]
@all-contributors bot please add @sarahhaggarty for docs
